version: '3.8'

services:
  telconova:
    image: telconova-app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${HIBERNATE_DIALECT}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3